[postgres]
host = "10.30.102.80"
port = "5432"
database = "vicidial2023"
user = "datateam"
password = "datateam123"

[ssh]
serverssh = '10.30.102.80'
userssh = 'carlos'
sshpass = 'autopasion987'
sshlocalhost = '127.0.0.1'
